_IMAGE_SIZES = {'CelebA': 64, 'CIFAR10': 32, 'MNIST': 28}
_COLOR_CHANNELS = {'CelebA': 3, 'CIFAR10': 3, 'MNIST': 1}

# Dataset
DATASET = 'CelebA'
DATA_PATH = '../Dataset/' + DATASET

# Image
IMG_SIZE = _IMAGE_SIZES[DATASET]
NUM_CHANNELS = _COLOR_CHANNELS[DATASET]

# Model
NUM_FILTERS = 64
LATENT_DIM = 100

# Resource
NGPU = 4

# Training
BATCH_SIZE = 128
EPOCHS = 20
LR = 2e-4
BETA1 = 0.5
REAL_LABEL = 1
FAKE_LABEL = 0
PRINT_EVERY = 1